# Autogenerated wrapper script for difmap_jll for x86_64-linux-musl-libgfortran3
export difmap

using PGPLOT_jll
using Xorg_libX11_jll
using Ncurses_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("difmap")
JLLWrappers.@declare_executable_product(difmap)
function __init__()
    JLLWrappers.@generate_init_header(PGPLOT_jll, Xorg_libX11_jll, Ncurses_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        difmap,
        "bin/difmap",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
